### ISSUE TITLE
error with `generate-token` command

### ISSUE THREAD

**Issue by OskarStark** [lexik/LexikJWTAuthenticationBundle#519]
```
lcobucci/jwt                             3.2.2              A simple library to work with JSON Web Token and JSON Web Signature
lexik/jwt-authentication-bundle          v2.5.1             This bundle provides JWT authentication for your Symfony REST API
```

```
Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "Sha256" from namespace "Lcobucci\JWT\Signer\Rsa".
Did you forget a "use" statement for another namespace? in /var/www/vendor/lexik/jwt-authentication-bundle/Services/JWSProvider/LcobucciJWSProvider.php:138
Stack trace:
#0 /var/www/vendor/lexik/jwt-authentication-bundle/Services/JWSProvider/LcobucciJWSProvider.php(67): Lexik\Bundle\JWTAuthenticationBundle\Services\JWSProvider\LcobucciJWSProvider->getSignerForAlgorithm('RS256')
#1 /var/www/var/cache/dev/ContainerHX3MWYF/getLexikJwtAuthentication_EncoderService.php(18): Lexik\Bundle\JWTAuthenticationBundle\Services\JWSProvider\LcobucciJWSProvider->__construct(Object(Lexik\Bundle\JWTAuthenticationBundle\Services\KeyLoader\RawKeyLoader), 'openssl', 'RS256', 3600, 0)
#2 /var/www/var/cache/dev/ContainerHX3MWYF/srcDevDebugProjectContainer.php(851): require('/var/www/var/ca...')
#3 /var/www/var/cache/dev/ContainerHX3MWYF/getLexikJwtAuthentication_JwtManagerService.php(13): Cont in /var/www/vendor/lexik/jwt-authentication-bundle/Services/JWSProvider/LcobucciJWSProvider.php on line 138
```

do you need any other info?

**Comment by chalasr** [comment]
Hey. That's weird, class `Lcobucci\JWT\Signer\RSA\Sha256 does exist, can't you find it in your vendors?
The command runs fine on my side with the same version of lcobucci/jwt. Can sound silly but perhaps try deleting your `vendor/` and `cache/` directories and reinstall?

**Comment by OskarStark** [comment]
Hey @chalasr 

![screenshot 2018-07-02 14 16 00](https://user-images.githubusercontent.com/995707/42163369-810b8fec-7e02-11e8-9079-f98453141da6.png)

weird, now it works 🤦‍♂️  

Thanks for your feedback, I close here...
