### ISSUE TITLE
Controller for authentication not found - only in tests

### ISSUE THREAD

**Issue by antond1990** [lexik/LexikJWTAuthenticationBundle#867]
When I run unit/functional tests to test retrieving a jwt token, I have different behavior than when I run the request via Postman, for example. When I run the request in Postman, I get a token. I'm using Symfony version: 5.3 and PHPUnit 9.5.4.

Security config:
```
security:
  encoders:
    App\Entity\User:
      algorithm: auto

  providers:
    # used to reload user from session & other features (e.g. switch_user)
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    login:
      pattern:  ^/api/login
      stateless: true
      anonymous: true
      provider: app_user_provider
      json_login:
        check_path:               /api/login_check
        success_handler:          lexik_jwt_authentication.handler.authentication_success
        failure_handler:          lexik_jwt_authentication.handler.authentication_failure

    api:
      pattern:   ^/api
      stateless: true
      guard:
        authenticators:
          - lexik_jwt_authentication.jwt_token_authenticator

  access_control:
    - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
```

My test:
```
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class JwtAuthTest extends WebTestCase
{

    public function testAuth()
    {
        $client = static::createClient();

        $crawler = $client->request('POST', '/api/login_check', [
            'headers' => [
                'Content-Type' => 'application/json',
            ],
            'body' => json_encode([
                'username' => 'test@email.de',
                'password' => 'test',
            ]),
        ]);

        $this->assertResponseStatusCodeSame(200, $client->getResponse()->getStatusCode());

        $responseData = json_decode($client->getResponse()->getContent(), true);

        $this->assertArrayHasKey('token', $responseData);
    }

}
```

Error:
```

/srv/api/vendor/symfony/framework-bundle/Test/BrowserKitAssertionsTrait.php:137
/srv/api/vendor/symfony/framework-bundle/Test/BrowserKitAssertionsTrait.php:38
/srv/api/tests/Api/JwtAuthTest.php:24
/srv/api/vendor/phpunit/phpunit/phpunit:61

Caused by
ErrorException: Unable to find the controller for path "/api/login_check". The route is wrongly configured. in /srv/api/vendor/symfony/http-kernel/HttpKernel.php:141
Stack trace:
#0 /srv/api/vendor/symfony/framework-bundle/Test/BrowserKitAssertionsTrait.php(38): Symfony\Bundle\FrameworkBundle\Test\WebTestCase::assertThatForResponse(Object(Symfony\Component\HttpFoundation\Test\Constraint\ResponseStatusCodeSame), '404')
#1 /srv/api/tests/Api/JwtAuthTest.php(24): Symfony\Bundle\FrameworkBundle\Test\WebTestCase::assertResponseStatusCodeSame(200, '404')
#2 /srv/api/vendor/phpunit/phpunit/src/Framework/TestCase.php(1526): App\Tests\Api\JwtAuthTest->testAuth()
#3 /srv/api/vendor/phpunit/phpunit/src/Framework/TestCase.php(1132): PHPUnit\Framework\TestCase->runTest()
#4 /srv/api/vendor/phpunit/phpunit/src/Framework/TestResult.php(722): PHPUnit\Framework\TestCase->runBare()
#5 /srv/api/vendor/phpunit/phpunit/src/Framework/TestCase.php(884): PHPUnit\Framework\TestResult->run(Object(App\Tests\Api\JwtAuthTest))
#6 /srv/api/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#7 /srv/api/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#8 /srv/api/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#9 /srv/api/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(667): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#10 /srv/api/vendor/phpunit/phpunit/src/TextUI/Command.php(143): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\Framework\TestSuite), Array, Array, true)
#11 /srv/api/vendor/phpunit/phpunit/src/TextUI/Command.php(96): PHPUnit\TextUI\Command->run(Array, true)
#12 /srv/api/vendor/phpunit/phpunit/phpunit(61): PHPUnit\TextUI\Command::main()
#13 /srv/api/bin/phpunit(4): require('/srv/api/vendor...')
#14 {main}
```

There is no special configuration for the test environment.

**Comment by antond1990** [comment]
It's not a bug.

The request must be executed like this:

```
$jsonData = json_encode([
    'username' => 'test@email.de',
    'password' => 'test',
]);
$crawler = $client->request('POST', '/api/login_check', [], [], [], $jsonData);
```
